name: CI Papi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: alpine-3.14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: CSet-up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      
