name: CI Papi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependeces
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
