name: CI Papi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: alpine:3.14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Install dependencies
        run: yarn install
        
      - name: Build website
        run: npm run build

      - run: npm run test:unit:all
      
