name: CI Papi

on:
  push:
    branches: [ci/cd]
  pull_request:
    branches: [ci/cd]

jobs:
  build:
      runs-on: ubuntu-20.04
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
            node-version: '14'
      - name: Build Docker image
        run: |
          docker build -t papi .
          docker save -o papi.tar papi

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: papi-artifact
          path: papi.tar
