name: CI Papi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: docker build -t papi:v1.0.0 .
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install || exit 1
        
      - name: Build website
        run: npm run build || exit 1
        
      - name: List contents of test directory
        run: ls -R test || exit 1

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: install-build
          path: test/helpers

  test: 
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: install-build

      - name: Run tests in Docker container
        run: docker run my-app npm test || exit 1

      - name: Test app
        run: npm run test || exit 1
  
