name: CI Papi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: CSet-up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependecies
        run: yarn install
      - run: ls
      - name: Build app
        run: npm run build
      - name: Build and upload artifacts for all projects
        run: |
          for dir in packages/*/; do
            echo "Building and uploading artifacts for project in directory: $dir"
            cd "$dir" || exit 1
            npm run build || exit 1
            cd ..
            echo "::set-env name=papi::$(basename "$dir")"
            echo "::set-env name=.::$dir"
            echo "::add-mask::$dir"
            echo "::group::Upload Artifacts"
            echo "Uploading artifacts for project: $(basename "$dir")"
            echo "Path: $dir/dist"
            upload-artifact@v2
              name: $(basename "$dir")-build
              path: "$dir/dist"
              echo "::endgroup::"
            done
