name: CI Papi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependeces
        run: npm install --legacy-peer-deps
      - name: Install dep
        run: yarn upgrade
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
