name: CI Papi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: CSet-up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependecies
        run: yarn install
      - run: ls
      - name: Build app
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
        
      - run: ls
      - name: Test all 
        run: npm run test:unit:all
      
      
