name: CI Papi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: docker build -t papi:v1.0.0 -f Dockerfile .
        
      - name: Archive Docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: .  # Archiva la imagen Docker en la raíz del repositorio
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build website
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: install-build
          path: test/helpers

  test: 
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: .
          
      - name: Run tests in Docker container
        run: docker run papi:v1.0.0 npm test
        
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: install-build
          path: test/helpers

      - name: Test app
        run: npm run test
  
